version: "3"

services:
  server:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./out:/srv
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.http.routers.automotron-site.rule=Host(`automotron.io`)"
      - "traefik.http.routers.automotron-site.tls.certresolver=le"
      - "traefik.http.routers.automotron-site.entrypoints=websecure"
      - "traefik.docker.network=traefik-external"
    networks:
      - traefik-external

networks:
  traefik-external:
    external: true
