name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
      - uses: appleboy/scp-action@master
        name: SCP
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: out
          target: automotron-site/out
          rm: true
      - uses: appleboy/ssh-action@master
        name: Deploy via SSH
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          timeout: 5m
          command_timeout: 5m
          script: |
            cd automotron-site
            docker-compose up -d
